# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = S:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = S:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Code\c\game-gl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Code\c\game-gl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	S:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	S:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\c\game-gl\CMakeFiles D:\Code\c\game-gl\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\c\game-gl\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glad.dir\build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/build
.PHONY : game/fast

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Util.o: src/Util.cpp.o
.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i
.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s
.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/Vertex.o: src/Vertex.cpp.o
.PHONY : src/Vertex.o

# target to build an object file
src/Vertex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Vertex.cpp.o
.PHONY : src/Vertex.cpp.o

src/Vertex.i: src/Vertex.cpp.i
.PHONY : src/Vertex.i

# target to preprocess a source file
src/Vertex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Vertex.cpp.i
.PHONY : src/Vertex.cpp.i

src/Vertex.s: src/Vertex.cpp.s
.PHONY : src/Vertex.s

# target to generate assembly for a file
src/Vertex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/Vertex.cpp.s
.PHONY : src/Vertex.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glad.dir\build.make CMakeFiles/glad.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glad.dir\build.make CMakeFiles/glad.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glad.dir\build.make CMakeFiles/glad.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math/plane.o: src/math/plane.cpp.o
.PHONY : src/math/plane.o

# target to build an object file
src/math/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/plane.cpp.o
.PHONY : src/math/plane.cpp.o

src/math/plane.i: src/math/plane.cpp.i
.PHONY : src/math/plane.i

# target to preprocess a source file
src/math/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/plane.cpp.i
.PHONY : src/math/plane.cpp.i

src/math/plane.s: src/math/plane.cpp.s
.PHONY : src/math/plane.s

# target to generate assembly for a file
src/math/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/plane.cpp.s
.PHONY : src/math/plane.cpp.s

src/math/polar.o: src/math/polar.cpp.o
.PHONY : src/math/polar.o

# target to build an object file
src/math/polar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/polar.cpp.o
.PHONY : src/math/polar.cpp.o

src/math/polar.i: src/math/polar.cpp.i
.PHONY : src/math/polar.i

# target to preprocess a source file
src/math/polar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/polar.cpp.i
.PHONY : src/math/polar.cpp.i

src/math/polar.s: src/math/polar.cpp.s
.PHONY : src/math/polar.s

# target to generate assembly for a file
src/math/polar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/polar.cpp.s
.PHONY : src/math/polar.cpp.s

src/math/spherical.o: src/math/spherical.cpp.o
.PHONY : src/math/spherical.o

# target to build an object file
src/math/spherical.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/spherical.cpp.o
.PHONY : src/math/spherical.cpp.o

src/math/spherical.i: src/math/spherical.cpp.i
.PHONY : src/math/spherical.i

# target to preprocess a source file
src/math/spherical.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/spherical.cpp.i
.PHONY : src/math/spherical.cpp.i

src/math/spherical.s: src/math/spherical.cpp.s
.PHONY : src/math/spherical.s

# target to generate assembly for a file
src/math/spherical.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/math/spherical.cpp.s
.PHONY : src/math/spherical.cpp.s

src/mesh/circle.o: src/mesh/circle.cpp.o
.PHONY : src/mesh/circle.o

# target to build an object file
src/mesh/circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/circle.cpp.o
.PHONY : src/mesh/circle.cpp.o

src/mesh/circle.i: src/mesh/circle.cpp.i
.PHONY : src/mesh/circle.i

# target to preprocess a source file
src/mesh/circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/circle.cpp.i
.PHONY : src/mesh/circle.cpp.i

src/mesh/circle.s: src/mesh/circle.cpp.s
.PHONY : src/mesh/circle.s

# target to generate assembly for a file
src/mesh/circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/circle.cpp.s
.PHONY : src/mesh/circle.cpp.s

src/mesh/cube.o: src/mesh/cube.cpp.o
.PHONY : src/mesh/cube.o

# target to build an object file
src/mesh/cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/cube.cpp.o
.PHONY : src/mesh/cube.cpp.o

src/mesh/cube.i: src/mesh/cube.cpp.i
.PHONY : src/mesh/cube.i

# target to preprocess a source file
src/mesh/cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/cube.cpp.i
.PHONY : src/mesh/cube.cpp.i

src/mesh/cube.s: src/mesh/cube.cpp.s
.PHONY : src/mesh/cube.s

# target to generate assembly for a file
src/mesh/cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/cube.cpp.s
.PHONY : src/mesh/cube.cpp.s

src/mesh/import.o: src/mesh/import.cpp.o
.PHONY : src/mesh/import.o

# target to build an object file
src/mesh/import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/import.cpp.o
.PHONY : src/mesh/import.cpp.o

src/mesh/import.i: src/mesh/import.cpp.i
.PHONY : src/mesh/import.i

# target to preprocess a source file
src/mesh/import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/import.cpp.i
.PHONY : src/mesh/import.cpp.i

src/mesh/import.s: src/mesh/import.cpp.s
.PHONY : src/mesh/import.s

# target to generate assembly for a file
src/mesh/import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/import.cpp.s
.PHONY : src/mesh/import.cpp.s

src/mesh/line_strip.o: src/mesh/line_strip.cpp.o
.PHONY : src/mesh/line_strip.o

# target to build an object file
src/mesh/line_strip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/line_strip.cpp.o
.PHONY : src/mesh/line_strip.cpp.o

src/mesh/line_strip.i: src/mesh/line_strip.cpp.i
.PHONY : src/mesh/line_strip.i

# target to preprocess a source file
src/mesh/line_strip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/line_strip.cpp.i
.PHONY : src/mesh/line_strip.cpp.i

src/mesh/line_strip.s: src/mesh/line_strip.cpp.s
.PHONY : src/mesh/line_strip.s

# target to generate assembly for a file
src/mesh/line_strip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/line_strip.cpp.s
.PHONY : src/mesh/line_strip.cpp.s

src/mesh/mesh.o: src/mesh/mesh.cpp.o
.PHONY : src/mesh/mesh.o

# target to build an object file
src/mesh/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/mesh.cpp.o
.PHONY : src/mesh/mesh.cpp.o

src/mesh/mesh.i: src/mesh/mesh.cpp.i
.PHONY : src/mesh/mesh.i

# target to preprocess a source file
src/mesh/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/mesh.cpp.i
.PHONY : src/mesh/mesh.cpp.i

src/mesh/mesh.s: src/mesh/mesh.cpp.s
.PHONY : src/mesh/mesh.s

# target to generate assembly for a file
src/mesh/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/mesh.cpp.s
.PHONY : src/mesh/mesh.cpp.s

src/mesh/plane.o: src/mesh/plane.cpp.o
.PHONY : src/mesh/plane.o

# target to build an object file
src/mesh/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/plane.cpp.o
.PHONY : src/mesh/plane.cpp.o

src/mesh/plane.i: src/mesh/plane.cpp.i
.PHONY : src/mesh/plane.i

# target to preprocess a source file
src/mesh/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/plane.cpp.i
.PHONY : src/mesh/plane.cpp.i

src/mesh/plane.s: src/mesh/plane.cpp.s
.PHONY : src/mesh/plane.s

# target to generate assembly for a file
src/mesh/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/plane.cpp.s
.PHONY : src/mesh/plane.cpp.s

src/mesh/quad.o: src/mesh/quad.cpp.o
.PHONY : src/mesh/quad.o

# target to build an object file
src/mesh/quad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/quad.cpp.o
.PHONY : src/mesh/quad.cpp.o

src/mesh/quad.i: src/mesh/quad.cpp.i
.PHONY : src/mesh/quad.i

# target to preprocess a source file
src/mesh/quad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/quad.cpp.i
.PHONY : src/mesh/quad.cpp.i

src/mesh/quad.s: src/mesh/quad.cpp.s
.PHONY : src/mesh/quad.s

# target to generate assembly for a file
src/mesh/quad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/quad.cpp.s
.PHONY : src/mesh/quad.cpp.s

src/mesh/sphere.o: src/mesh/sphere.cpp.o
.PHONY : src/mesh/sphere.o

# target to build an object file
src/mesh/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/sphere.cpp.o
.PHONY : src/mesh/sphere.cpp.o

src/mesh/sphere.i: src/mesh/sphere.cpp.i
.PHONY : src/mesh/sphere.i

# target to preprocess a source file
src/mesh/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/sphere.cpp.i
.PHONY : src/mesh/sphere.cpp.i

src/mesh/sphere.s: src/mesh/sphere.cpp.s
.PHONY : src/mesh/sphere.s

# target to generate assembly for a file
src/mesh/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/sphere.cpp.s
.PHONY : src/mesh/sphere.cpp.s

src/mesh/torus.o: src/mesh/torus.cpp.o
.PHONY : src/mesh/torus.o

# target to build an object file
src/mesh/torus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/torus.cpp.o
.PHONY : src/mesh/torus.cpp.o

src/mesh/torus.i: src/mesh/torus.cpp.i
.PHONY : src/mesh/torus.i

# target to preprocess a source file
src/mesh/torus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/torus.cpp.i
.PHONY : src/mesh/torus.cpp.i

src/mesh/torus.s: src/mesh/torus.cpp.s
.PHONY : src/mesh/torus.s

# target to generate assembly for a file
src/mesh/torus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/mesh/torus.cpp.s
.PHONY : src/mesh/torus.cpp.s

src/utility/log.o: src/utility/log.cpp.o
.PHONY : src/utility/log.o

# target to build an object file
src/utility/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/log.cpp.o
.PHONY : src/utility/log.cpp.o

src/utility/log.i: src/utility/log.cpp.i
.PHONY : src/utility/log.i

# target to preprocess a source file
src/utility/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/log.cpp.i
.PHONY : src/utility/log.cpp.i

src/utility/log.s: src/utility/log.cpp.s
.PHONY : src/utility/log.s

# target to generate assembly for a file
src/utility/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/log.cpp.s
.PHONY : src/utility/log.cpp.s

src/utility/random.o: src/utility/random.cpp.o
.PHONY : src/utility/random.o

# target to build an object file
src/utility/random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/random.cpp.o
.PHONY : src/utility/random.cpp.o

src/utility/random.i: src/utility/random.cpp.i
.PHONY : src/utility/random.i

# target to preprocess a source file
src/utility/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/random.cpp.i
.PHONY : src/utility/random.cpp.i

src/utility/random.s: src/utility/random.cpp.s
.PHONY : src/utility/random.s

# target to generate assembly for a file
src/utility/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/random.cpp.s
.PHONY : src/utility/random.cpp.s

src/utility/time.o: src/utility/time.cpp.o
.PHONY : src/utility/time.o

# target to build an object file
src/utility/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/time.cpp.o
.PHONY : src/utility/time.cpp.o

src/utility/time.i: src/utility/time.cpp.i
.PHONY : src/utility/time.i

# target to preprocess a source file
src/utility/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/time.cpp.i
.PHONY : src/utility/time.cpp.i

src/utility/time.s: src/utility/time.cpp.s
.PHONY : src/utility/time.s

# target to generate assembly for a file
src/utility/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/src/utility/time.cpp.s
.PHONY : src/utility/time.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... game
	@echo ... glad
	@echo ... src/Shader.o
	@echo ... src/Shader.i
	@echo ... src/Shader.s
	@echo ... src/Util.o
	@echo ... src/Util.i
	@echo ... src/Util.s
	@echo ... src/Vertex.o
	@echo ... src/Vertex.i
	@echo ... src/Vertex.s
	@echo ... src/glad.o
	@echo ... src/glad.i
	@echo ... src/glad.s
	@echo ... src/main.o
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/math/plane.o
	@echo ... src/math/plane.i
	@echo ... src/math/plane.s
	@echo ... src/math/polar.o
	@echo ... src/math/polar.i
	@echo ... src/math/polar.s
	@echo ... src/math/spherical.o
	@echo ... src/math/spherical.i
	@echo ... src/math/spherical.s
	@echo ... src/mesh/circle.o
	@echo ... src/mesh/circle.i
	@echo ... src/mesh/circle.s
	@echo ... src/mesh/cube.o
	@echo ... src/mesh/cube.i
	@echo ... src/mesh/cube.s
	@echo ... src/mesh/import.o
	@echo ... src/mesh/import.i
	@echo ... src/mesh/import.s
	@echo ... src/mesh/line_strip.o
	@echo ... src/mesh/line_strip.i
	@echo ... src/mesh/line_strip.s
	@echo ... src/mesh/mesh.o
	@echo ... src/mesh/mesh.i
	@echo ... src/mesh/mesh.s
	@echo ... src/mesh/plane.o
	@echo ... src/mesh/plane.i
	@echo ... src/mesh/plane.s
	@echo ... src/mesh/quad.o
	@echo ... src/mesh/quad.i
	@echo ... src/mesh/quad.s
	@echo ... src/mesh/sphere.o
	@echo ... src/mesh/sphere.i
	@echo ... src/mesh/sphere.s
	@echo ... src/mesh/torus.o
	@echo ... src/mesh/torus.i
	@echo ... src/mesh/torus.s
	@echo ... src/utility/log.o
	@echo ... src/utility/log.i
	@echo ... src/utility/log.s
	@echo ... src/utility/random.o
	@echo ... src/utility/random.i
	@echo ... src/utility/random.s
	@echo ... src/utility/time.o
	@echo ... src/utility/time.i
	@echo ... src/utility/time.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

