
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "S:/msys64/mingw64/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.22631 - AMD64
...
